### ISSUE TITLE
support secure connections to backends (SSL/HTTPS)

### ISSUE THREAD

**Issue by yanns** [hjr3/weldr#46]
Support backends using a SSL certificate.
Points to pay attention for:
- how much do we check the validity of the SSL certificate?
- having the possibility not to check the validity of the SSL certificate (auto-signed certificates for development)
- using client SSL certificates for a secure internal network?

**Comment by hjr3** [comment]
We can also pin to a specific certs fingerprint.

**Comment by hjr3** [comment]
https://crates.io/crates/hyper-tls is in progress for the client.
