### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by hjr3** [hjr3/weldr#69]
Due to feedback about a naming similarity, I am looking for a new project name. I am using http://ivantomic.com/projects/ospnc/ to try and make sure the next name is unused.

Current options:

   * spinet
   * celerity
   * levity
   * coller
   * compt
   * rust-spigot
   * yap
   * symmetry
   * plenus
   * welder (weldr)
   * lever
   * braze

**Comment by smaslennikov** [comment]
How about rusty-spigot?

**Comment by yanns** [comment]
YAP? (Yet Another Proxy)
😉

**Comment by hjr3** [comment]
After thinking about this over the past few days, I like something that complements that fact that multiple Rust web frameworks take the form of some base metal. Examples are nickel and iron. There are other Rust projects that use a base metal for a name too.

Welding is something that combines metals. We can think of this proxy as a welding multiple servers together into a single cluster. Naming the project _welder_ was a bit too direct or me. I am dropping the second `e` in a classic form of tech playfulness. The new project name is _weldr_!

**Comment by oldsj** [comment]
Awesome I was going to throw a vote in for weldr too but looks like I'm too late
