### ISSUE TITLE
Save in rpm, deb and docker repo/registries

### ISSUE THREAD

**Issue by hjr3** [hjr3/weldr#70]
I have https://packagecloud.io/hjr3/weldr setup. The proxy binary should be a completely static library. Once that library is created, rpm and deb packages should be created to make it easy for people to mange (install/uninstall) the proxy.

I have used [fpm](https://github.com/jordansissel/fpm) in the past in lieu of creating separate Vagrant boxes for each OS. Especially since it is a static binary.

**Comment by yanns** [comment]
and do not forget docker. It's very convenient for cloud-based infrastructure.
And I described how to create a statically linked binary: https://github.com/hjr3/alacrity/blob/master/DOCKER.md

Does it make sense to change the name before?

**Comment by hjr3** [comment]
@yanns yes, good call. You had done a lot of the docker work and I forgot to consider storing it in the docker registry/repository.

**Comment by maniankara** [comment]
Hi @hjr3 and @yanns I can give it a try. Seems [docker](https://github.com/hjr3/weldr/blob/master/Dockerfile) part is already done? 
It might be an obvious question, can you tell should these package creations be done as a part of CI (in travis)?

**Comment by hjr3** [comment]
@maniankara the `Docker` file exists, the remaining work would be storing it in the docker registry when we do a release.

i think creating packages on every commit to the master branch is excessive at this point. we can use https://docs.travis-ci.com/user/deployment/packagecloud/ in conjunction with https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A (using `on: tags: true`)

**Comment by hjr3** [comment]
@maniankara let me know your username so i can add you as a collaborator on https://packagecloud.io/hjr3/weldr

**Comment by maniankara** [comment]
@hjr3 its the same as my github account :)

**Comment by hjr3** [comment]
Closed by #84
