### ISSUE TITLE
Make health check timer configurable

### ISSUE THREAD

**Issue by hjr3** [hjr3/weldr#93]
The code in health.rs does a check every 5 seconds. We should make it configurable.

Note: While we are waiting on a configuration file format, we can set the value in src/alacrity.rs or something. The important part is that the health check code is not hardcoding the value.

**Comment by maniankara** [comment]
@hjr3 something like this simple may be?

**Comment by hjr3** [comment]
Fixed in https://github.com/hjr3/weldr/pull/99
