### ISSUE TITLE
Allow for multiple errors in merge3

### ISSUE THREAD

**Issue by hjr3** [hjr3/weldr#94]
The merge3 code was taken from the `futures/stream/merge.rs` code in the futures-rs crate. Currently, there is only support for one error but there is the possibility that we have two errors that need to be stored.

**Comment by maniankara** [comment]
@hjr3 can you be a bit more descriptive on this?

**Comment by hjr3** [comment]
Closing this as `merge3` should not be needed anymore for https://github.com/hjr3/weldr/pull/98

**Comment by hjr3** [comment]
Hi Anoop,

I have been working on https://github.com/hjr3/weldr/pull/98 which does not
require merg3 anymore, so I closed it. I triaged the remaining open issues
and I believe they are all valid.
